In [2]:
### Import Statements ###
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_selection import RFE
import seaborn as sns
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import SelectKBest, chi2
%matplotlib inline
from sklearn.model_selection import GridSearchCV,train_test_split

In [8]:
df = pd.read_csv('criminal_train.csv')
df.head(11457)

,PERID,IFATHER,NRCH17_2,IRHHSIZ2,IIHHSIZ2,IRKI17_2,IIKI17_2,IRHH65_2,IIHH65_2,PRXRETRY,...,TOOLONG,TROUBUND,PDEN10,COUTYP2,MAIIN102,AIIND102,ANALWT_C,VESTR,VEREP,Criminal
0,25095143,4,2,4,1,3,1,1,1,99,...,1,2,1,1,2,2,3884.805998,40026,1,0
1,13005143,4,1,3,1,2,1,1,1,99,...,2,2,2,3,2,2,1627.108106,40015,2,1
2,67415143,4,1,2,1,2,1,1,1,99,...,2,2,2,3,2,2,4344.957980,40024,1,0
3,70925143,4,0,2,1,1,1,1,1,99,...,2,2,1,1,2,2,792.521931,40027,1,0
4,75235143,1,0,6,1,4,1,1,1,99,...,2,2,2,2,2,2,1518.118526,40001,2,0
5,47745143,4,0,2,1,1,1,1,1,99,...,2,2,2,3,2,2,9129.229124,40035,2,0
6,33145143,4,3,6,1,4,1,1,1,99,...,2,2,2,2,2,2,6561.895497,40043,2,0
7,63765143,4,2,4,1,3,1,1,1,99,...,2,2,2,2,2,2,3341.718873,40006,2,0
8,57796143,4,1,3,1,2,1,1,1,99,...,2,2,2,1,2,2,3384.147888,40021,2,0
9,66416143,4,0,1,1,1,1,2,1,99,...,2,2,1,1,2,2,2636.943978,40006,1,0
10,51916143,4,0,1,1,1,1,1,1,99,...,98,98,2,3,2,2,3026.110863,40044,1,0
11,40016143,4,0,4,1,3,1,1,1,99,...,2,2,1,1,2,2,4196.225953,40025,2,0
12,99116143,4,0,2,1,1,1,2,1,99,...,2,2,2,2,2,2,20905.427440,40042,1,0
13,85326143,1,0,3,1,2,1,1,1,99,...,2,2,1,1,2,2,2671.376188,40035,2,0
14,63336143,1,0,5,1,4,1,1,1,99,...,2,2,1,1,2,2,1430.775669,40020,1,0
15,64946143,4,3,5,1,4,1,1,1,99,...,2,2,1,1,2,2,1041.374975,40004,2,0
16,73856143,4,0,2,1,1,1,1,1,99,...,2,2,2,2,2,2,5014.378391,40023,1,0
17,82956143,4,2,4,1,3,1,1,1,99,...,2,2,3,3,2,2,4757.271596,40033,1,0
18,65276143,4,2,3,1,3,1,1,1,99,...,2,2,2,2,2,2,2784.880401,40025,2,0
19,58307143,1,0,4,1,3,1,1,1,99,...,2,2,2,3,2,2,330.258076,40036,1,0
20,67407143,1,0,4,1,3,1,1,1,99,...,2,2,2,3,2,2,2398.833215,40028,2,0
21,83427143,4,1,3,1,2,1,1,1,99,...,2,2,2,2,2,2,4247.334140,40008,2,0
22,68447143,1,0,5,1,3,1,2,1,99,...,2,1,1,1,2,2,2432.035890,40007,2,0
23,65177143,4,0,2,1,1,1,3,1,99,...,2,2,2,3,2,2,9429.142633,40010,2,0
24,77787143,1,0,6,1,4,1,1,1,99,...,2,2,2,3,1,1,791.405193,40012,2,0
25,96887143,4,0,4,1,2,1,1,1,99,...,2,2,1,1,2,2,751.207301,40046,1,0
26,46218143,4,0,3,1,2,3,1,3,99,...,2,2,2,3,2,2,3327.695904,40042,2,0
27,15938143,4,0,1,1,1,1,1,1,99,...,2,2,2,2,1,1,7913.574798,40012,2,0
28,15268143,4,0,3,1,1,1,1,1,99,...,2,2,2,3,2,2,416.917733,40036,1,0
29,79868143,1,0,4,1,3,1,1,1,99,...,2,2,2,2,2,2,432.992914,40016,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11427,63482894,4,2,3,1,3,1,1,1,99,...,1,2,1,1,2,2,4908.927473,40045,2,0
11428,27082894,4,1,3,1,2,1,1,1,99,...,2,2,2,2,2,2,4054.179142,40005,1,0
11429,65613894,2,0,3,1,3,1,1,1,99,...,2,2,2,3,2,2,2832.378200,40042,1,0
11430,36323894,4,0,4,1,1,1,1,1,99,...,2,2,2,2,2,2,6599.926734,40009,1,0
11431,32533894,4,2,5,1,3,1,2,1,99,...,2,2,2,2,2,2,6768.795076,40049,1,1
11432,90443894,1,0,3,1,2,1,1,1,99,...,2,2,1,1,2,2,2523.524349,40016,2,0
11433,57743894,1,0,5,1,4,1,1,1,99,...,2,2,2,2,2,2,1518.776960,40027,2,0
11434,85753894,1,0,2,1,2,1,1,1,99,...,2,2,1,1,2,2,2640.986157,40001,1,0
11435,54663894,4,2,4,1,3,1,1,1,99,...,2,2,1,1,2,2,5030.530944,40012,2,0
11436,19163894,4,1,3,1,2,1,1,1,99,...,2,2,1,1,2,2,9025.153764,40035,2,0
11437,83383894,4,1,3,1,2,1,1,1,99,...,2,2,2,2,2,2,13001.147740,40008,1,0
11438,10494894,4,0,5,1,3,1,1,1,99,...,2,2,2,2,2,2,3309.850178,40027,2,0
11439,87794894,4,0,3,1,1,1,1,1,99,...,2,2,2,2,2,2,1597.650156,40043,2,0
11440,72004894,4,0,2,1,1,1,3,1,99,...,2,2,2,1,2,2,1628.570585,40034,2,0
11441,75514894,4,0,2,1,1,1,1,1,99,...,2,2,1,1,2,2,664.498873,40045,2,0
11442,41914894,2,0,3,1,2,1,1,1,99,...,2,2,1,1,2,2,181.660400,40007,2,0
11443,55324894,4,0,2,1,1,1,1,1,99,...,2,2,2,1,2,2,1874.873135,40013,1,0
11444,23334894,4,0,3,1,1,1,1,1,99,...,2,2,1,1,2,2,1746.762816,40028,2,0
11445,39444894,1,0,4,1,3,1,1,1,99,...,2,2,2,2,2,2,3210.602791,40032,2,0
11446,47264894,4,1,2,1,2,1,1,1,99,...,2,2,2,2,2,2,8495.474637,40003,2,0
11447,91864894,1,0,4,1,2,1,1,1,99,...,2,2,1,1,2,2,4193.912130,40041,2,0
11448,13284894,4,3,5,1,4,1,1,1,99,...,2,2,2,3,2,2,269.063318,40014,1,0
11449,22384894,1,0,4,1,3,1,1,1,99,...,2,2,1,1,2,2,4265.119996,40025,2,0
11450,69684894,4,0,1,1,1,1,1,1,99,...,2,2,3,3,2,2,587.698999,40036,2,0
11451,57884894,4,0,2,1,1,1,1,1,99,...,2,2,2,3,2,2,824.047247,40027,2,0
11452,77495994,4,0,4,1,1,1,1,1,99,...,1,2,2,2,2,2,2014.669324,40009,1,0
11453,45405994,4,0,4,1,2,1,1,1,99,...,2,2,1,1,2,2,3336.989923,40012,1,0
11454,21615994,4,0,3,1,1,1,1,1,99,...,2,2,2,3,2,2,1417.784482,40034,1,0
11455,40715994,4,1,2,1,2,1,1,1,99,...,2,2,2,2,2,2,16441.605660,40042,2,0
11456,20525994,4,0,2,1,1,1,2,1,99,...,2,2,2,2,2,2,15372.309100,40049,1,0

In [3]:
'''from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(df)
scaled_features = scaler.transform(df)
df_feat = pd.DataFrame(scaled_features,columns=df.columns)
df_feat.head()'''

'from sklearn.preprocessing import StandardScaler\nscaler = StandardScaler()\nscaler.fit(df)\nscaled_features = scaler.transform(df)\ndf_feat = pd.DataFrame(scaled_features,columns=df.columns)\ndf_feat.head()'

In [4]:
'''from sklearn.decomposition import PCA
pca = PCA(n_components=50)
pca.fit(scaled_data)
x_pca = pd.DataFrame(pca.transform(scaled_data))
'''

'from sklearn.decomposition import PCA\npca = PCA(n_components=50)\npca.fit(scaled_data)\nx_pca = pd.DataFrame(pca.transform(scaled_data))\n'

In [5]:
'''df[df < 0] = 0
test = SelectKBest(score_func=chi2, k=65)
fit = test.fit(df.drop('Criminal',axis=1),df['Criminal'])
#print(len(fit.scores_))
features = fit.transform(df.drop('Criminal',axis=1))
# summarize selected features
print(features.shape)
dfy = pd.DataFrame(data=features,columns=range(1,66))
dfyc = pd.DataFrame(df['Criminal'],columns=['66'])
dfy = pd.concat([dfy,df['Criminal']],axis=1)'''

"df[df < 0] = 0\ntest = SelectKBest(score_func=chi2, k=65)\nfit = test.fit(df.drop('Criminal',axis=1),df['Criminal'])\n#print(len(fit.scores_))\nfeatures = fit.transform(df.drop('Criminal',axis=1))\n# summarize selected features\nprint(features.shape)\ndfy = pd.DataFrame(data=features,columns=range(1,66))\ndfyc = pd.DataFrame(df['Criminal'],columns=['66'])\ndfy = pd.concat([dfy,df['Criminal']],axis=1)"

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop('Criminal',axis=1), 
                                                    df['Criminal'], test_size=0.2, 
                                                    random_state=101)

In [4]:
from sklearn.ensemble import RandomForestRegressor,RandomForestClassifier
#rf = RandomForestClassifier() #default 
rf = RandomForestClassifier()
df = df.drop(df.columns[[4,21,22,24,36,37]], axis=1)

In [5]:
rf.fit(df.drop('Criminal',axis=1),df['Criminal'])

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [17]:
model=ExtraTreesClassifier()
parameters={'n_estimators':[500,600],'max_features':['log2'],'bootstrap':[False],'warm_start':[True],'criterion':["entropy"]}
best_model = GridSearchCV(rf,parameters,n_jobs=5,verbose=True)
best_model.fit(df.drop('Criminal',axis=1),df['Criminal'])
best_model.best_params_

Fitting 3 folds for each of 2 candidates, totalling 6 fits

[Parallel(n_jobs=5)]: Done   4 out of   6 | elapsed:  1.2min remaining:   35.7s
[Parallel(n_jobs=5)]: Done   6 out of   6 | elapsed:  1.7min finished

{'bootstrap': False,
 'criterion': 'entropy',
 'max_features': 'log2',
 'n_estimators': 500,
 'warm_start': True}

In [9]:
dft = pd.read_csv('criminal_test.csv')
dft.head(1145)

,PERID,IFATHER,NRCH17_2,IRHHSIZ2,IIHHSIZ2,IRKI17_2,IIKI17_2,IRHH65_2,IIHH65_2,PRXRETRY,...,POVERTY3,TOOLONG,TROUBUND,PDEN10,COUTYP2,MAIIN102,AIIND102,ANALWT_C,VESTR,VEREP
0,66583679,4,0,4,1,2,1,1,1,99,...,2,2,2,1,1,2,2,16346.795400,40020,1
1,35494679,4,0,4,1,1,1,1,1,99,...,3,2,2,1,1,2,2,3008.863906,40044,2
2,79424679,2,0,3,1,2,1,1,1,99,...,1,2,2,2,2,2,2,266.952503,40040,2
3,11744679,4,0,6,1,2,1,1,1,99,...,3,2,2,1,1,2,2,5386.928199,40017,1
4,31554679,1,0,4,1,3,1,1,1,99,...,3,2,1,1,1,2,2,173.489895,40017,1
5,83164679,1,0,6,1,4,1,1,1,99,...,1,2,2,1,1,2,2,562.268242,40035,2
6,58474679,4,0,2,1,1,1,2,1,99,...,2,1,2,1,1,2,2,24857.283570,40040,2
7,40695779,4,0,1,1,1,1,1,1,99,...,1,1,2,1,1,2,2,6219.428316,40015,2
8,39315779,4,0,2,1,1,1,1,1,99,...,3,2,2,2,3,2,2,5256.401262,40022,1
9,58415779,4,0,2,1,1,1,3,1,99,...,3,2,2,2,3,2,2,8081.240889,40023,1
10,23535779,4,0,2,1,1,1,1,1,99,...,3,2,2,1,1,2,2,3431.856903,40044,1
11,67275779,4,1,3,1,2,1,1,1,99,...,3,2,1,2,2,2,2,3759.142319,40044,2
12,93485779,2,0,6,1,4,1,1,1,99,...,2,2,2,2,2,2,2,974.948772,40019,2
13,29546779,4,0,2,1,1,1,1,1,99,...,3,2,1,2,2,2,2,1914.468602,40006,2
14,97556779,2,0,3,1,2,1,1,1,99,...,2,2,2,1,1,2,2,281.176495,40042,1
15,37797779,4,0,4,1,1,1,1,1,99,...,3,2,2,1,1,2,2,9088.623271,40007,2
16,36607779,4,0,5,1,3,1,1,1,99,...,1,2,2,2,2,2,2,3715.508104,40040,1
17,61727779,4,0,2,1,1,1,1,1,99,...,3,2,2,3,3,2,2,5661.847892,40035,2
18,20827779,4,3,5,1,4,1,1,1,99,...,2,2,2,2,3,2,2,377.644075,40047,2
19,52437779,4,0,2,1,1,1,2,1,99,...,2,2,1,2,2,2,2,12288.975580,40014,1
20,87267779,4,1,3,1,2,1,1,1,99,...,3,2,2,3,3,2,2,3824.418318,40029,2
21,33287779,4,0,2,1,1,1,1,1,99,...,3,2,2,3,3,2,2,218.879040,40048,1
22,30398779,4,0,2,1,1,1,1,1,99,...,3,2,2,2,2,1,1,3899.398591,40028,2
23,98598779,4,2,4,1,3,1,1,1,99,...,1,2,2,2,2,2,2,1429.069206,40005,2
24,41818779,1,0,6,1,4,1,1,1,99,...,2,2,2,2,2,2,2,671.369416,40047,1
25,69638779,4,0,2,1,1,1,1,1,99,...,3,2,2,2,2,2,2,6656.154985,40009,2
26,25748779,1,0,5,1,4,1,1,1,99,...,3,2,2,1,1,2,2,995.612630,40026,1
27,75368779,4,0,1,1,1,1,1,1,99,...,3,2,2,3,3,2,2,11359.873670,40033,1
28,99968779,4,0,4,1,1,1,2,1,99,...,3,2,2,2,2,2,2,5194.522223,40020,2
29,91578779,4,0,1,1,1,1,2,1,99,...,2,2,2,2,3,2,2,13987.779540,40050,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1115,49439299,4,0,1,1,1,1,2,1,99,...,3,2,2,2,3,2,2,8791.025463,40045,1
1116,81189299,4,1,3,1,2,1,1,1,99,...,2,2,2,2,2,2,2,3802.760300,40019,2
1117,47100299,4,0,2,1,1,1,1,1,99,...,3,2,2,1,1,2,2,6659.881614,40021,2
1118,40420299,4,0,4,1,1,1,2,1,99,...,1,2,2,2,3,2,2,2382.527274,40038,1
1119,79330299,4,2,4,1,3,1,1,1,99,...,1,2,2,2,2,2,2,6046.237976,40013,1
1120,20560299,4,3,5,1,4,1,1,1,99,...,3,2,2,3,3,2,2,7303.009258,40015,2
1121,89470299,1,0,4,1,3,1,1,1,99,...,1,2,2,2,2,2,2,4148.042874,40020,1
1122,64301299,4,0,6,1,4,1,1,1,99,...,3,2,2,2,3,1,1,12582.716520,40041,2
1123,31411299,4,0,3,1,1,1,1,1,99,...,3,2,2,2,2,2,2,1343.699198,40025,2
1124,11031299,4,0,3,1,1,1,3,1,99,...,2,2,2,2,2,1,1,2036.138502,40012,1
1125,52641299,4,3,5,1,4,1,1,1,99,...,1,2,2,2,3,2,2,677.840732,40003,1
1126,89941299,4,0,2,1,1,1,1,1,99,...,3,2,2,1,1,2,2,20141.847620,40008,2
1127,31171299,1,0,5,1,4,1,1,1,99,...,3,2,2,1,1,2,2,2690.310110,40047,1
1128,71792299,4,0,2,1,1,1,1,1,99,...,1,2,2,2,2,2,2,403.500373,40046,2
1129,59992299,4,0,2,1,1,1,3,1,99,...,3,1,2,1,1,2,2,5721.077196,40045,2
1130,64202299,4,0,3,1,1,1,1,1,99,...,2,1,2,2,2,2,2,2372.335795,40030,1
1131,61502299,1,0,4,1,2,1,1,3,99,...,2,2,2,2,3,2,2,1094.147896,40047,1
1132,93922299,4,0,3,1,1,1,1,1,99,...,3,2,2,1,1,2,2,4881.568172,40018,1
1133,38232299,1,0,4,1,3,1,1,1,99,...,3,1,1,2,3,2,2,2790.956795,40014,1
1134,52832299,1,0,4,1,3,1,1,1,99,...,3,2,2,1,1,2,2,6386.057022,40033,1
1135,79842299,4,0,2,1,1,1,3,1,99,...,2,2,2,2,3,2,2,601.288706,40044,1
1136,83252299,4,3,6,1,4,1,3,1,99,...,3,1,2,2,2,2,2,1056.234133,40031,1
1137,31452299,2,0,3,1,3,1,1,1,99,...,1,2,2,2,2,2,2,1282.460924,40030,2
1138,51262299,4,0,2,1,1,1,1,1,99,...,3,1,2,2,2,2,2,4922.881420,40030,1
1139,29462299,4,0,4,1,1,1,1,1,99,...,3,2,2,1,1,2,2,842.929013,40006,2
1140,95293299,4,0,3,1,1,1,2,1,99,...,1,2,1,1,1,2,2,4502.774058,40048,2
1141,17613299,4,0,1,1,1,1,1,1,99,...,2,2,2,2,2,1,1,3666.995680,40002,2
1142,35813299,4,0,2,1,1,1,3,1,99,...,3,2,2,2,3,2,2,8875.790827,40014,1
1143,20933299,2,0,4,1,3,1,1,1,99,...,1,2,2,2,2,2,2,2178.625928,40042,2
1144,41543299,4,0,3,1,2,1,1,1,99,...,3,2,2,2,3,2,2,2262.325252,40002,2

In [7]:
dft.shape

(11430, 71)

In [8]:
best_model.predict(dft)

NameError: name 'best_model' is not defined

In [9]:
final_predict = pd.DataFrame(best_model.predict(dft),columns=['Criminal'])
result = pd.DataFrame(dft['PERID'],columns=['PERID'])
result = pd.concat([result,final_predict],axis=1)
result['Criminal'].value_counts()

NameError: name 'best_model' is not defined

In [10]:
result.to_csv('final_predictions.csv',index=False)

NameError: name 'result' is not defined

In [11]:
dfs = pd.read_csv('final_predictions.csv')